FROM  italiangrid/build-centos7

RUN yum -y install pkgconfig swig libacl-devel \
  gpfs.base \
  lcmaps-without-gsi-devel \
  lcmaps-interface
USER build
ADD Makefile ./storm-native-libs.spec.in /home/build/
WORKDIR /home/build

CMD /bin/bash -c make
